title: "Ivry Échecs 94"
description: "Club d’échecs à Ivry-sur-Seine : initiation, progression, convivialité et compétitions."

url: "https://cool-klepon-f668fd.netlify.app"
baseurl: ""   # très important de le laisser vide

markdown: kramdown

exclude:
  - node_modules
  - README.md
